# Generated by Django 5.2.7 on 2025-10-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igati_app', '0004_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
